import { chromium } from 'playwright-core';
import { createServer } from 'node:http';
import { readFile, mkdir, writeFile } from 'node:fs/promises';
import assert from 'node:assert/strict';
import { pathToFileURL } from 'node:url';

await mkdir('qa', { recursive: true });
const server = createServer(async (req, res) => {
  const pathname = new URL(req.url, 'http://localhost').pathname;
  const filename = pathname.endsWith('control.html') ? 'control.html' : pathname.endsWith('/') || pathname.endsWith('index.html') ? 'index.html' : null;
  if (!filename) { res.writeHead(404).end(); return; }
  res.setHeader('Content-Type', 'text/html; charset=utf-8');
  res.end(await readFile('dist/' + filename));
});
await new Promise(resolve => server.listen(0, '127.0.0.1', resolve));
const base = 'http://127.0.0.1:' + server.address().port + '/panama-conecta-311/';
console.log('Servidor listo: ' + base);
const browser = await chromium.launch({ channel: 'msedge', timeout: 30000, args: ['--use-angle=swiftshader', '--enable-unsafe-swiftshader', '--ignore-gpu-blocklist'] });
console.log('Navegador abierto');
const report = { checks: [], errors: [] };
const check = name => { report.checks.push(name); console.log('OK ' + name); };
try {
  const host = await browser.newPage({ viewport: { width: 1366, height: 768 } });
  host.on('pageerror', error => (report.errors.push(error.message), console.error(error.message)));
  host.on('console', m => { if(m.type() === 'error') console.error('CONSOLE',m.text()); });
  console.log('Abriendo animación');
  await host.goto(base);
  console.log('HTML cargado');
  await host.waitForFunction(() => window.pc311?.getT, null, { timeout: 45000 });
  assert.equal(await host.evaluate(() => window.pc311.listo), true);
  assert.deepEqual(await host.evaluate(() => window.pc311.validar()), []);
  check('guion válido (subtítulos = locución)');
  await host.getByRole('button', { name: 'Control remoto', exact: true }).click();
  await host.getByRole('button', { name: 'Activar control', exact: true }).click();
  await host.waitForFunction(() => document.querySelector('.remote-link').value.length > 0, { timeout: 30000 });
  const link = await host.locator('.remote-link').inputValue();
  assert.ok(link.startsWith(base + 'control.html#'));
  check('sesión privada y ruta de repositorio');
  await host.screenshot({ path: 'qa/remoto-vinculacion.png' });
  const invalid = await browser.newPage();
  const invalidUrl = new URL(link);
  const invalidHash = new URLSearchParams(invalidUrl.hash.slice(1));
  invalidHash.set('clave', '00000000-0000-0000-0000-000000000000');
  invalidUrl.hash = invalidHash.toString();
  await invalid.goto(invalidUrl.href);
  await invalid.waitForTimeout(3500);
  assert.equal(await invalid.locator('#play').isDisabled(), true);
  check('clave incorrecta no habilita controles');
  await invalid.close();

  const remote = await browser.newPage({ viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true });
  remote.on('pageerror', error => report.errors.push(error.message));
  await remote.goto(link);
  await remote.waitForFunction(() => !document.querySelector('#play').disabled, { timeout: 30000 });
  await host.getByRole('button', { name: 'Cerrar', exact: true }).click();
  await remote.locator('#play').click();
  await host.waitForFunction(() => window.pc311.ui().reproduciendo);
  check('reproducir desde el teléfono');
  await remote.waitForTimeout(1200);
  const antesSalto = await host.evaluate(() => window.pc311.getT());
  await remote.locator('#forward').click();
  await host.waitForFunction(t => window.pc311.getT() > t + 4.5, antesSalto);
  assert.equal(await host.evaluate(() => window.pc311.ui().reproduciendo), true);
  check('+5 s durante la reproducción sigue reproduciendo');
  await remote.waitForTimeout(1200);
  await remote.locator('#pause').click();
  await host.waitForFunction(() => !window.pc311.ui().reproduciendo);
  const paused = await host.evaluate(() => window.pc311.getT());
  await remote.waitForTimeout(600);
  assert.equal(await host.evaluate(() => window.pc311.getT()), paused);
  check('pausa mantiene el cuadro');
  await remote.locator('#forward').click();
  await host.waitForFunction(t => window.pc311.getT() > t + 4, paused);
  check('avanzar cinco segundos');
  await remote.screenshot({ path: 'qa/remoto-telefono.png' });
  assert.equal(await remote.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
  check('control móvil sin desbordamiento horizontal');
  await remote.locator('#restart').click();
  await host.waitForFunction(() => window.pc311.getT() === 0 && !window.pc311.ui().reproduciendo);
  check('reiniciar vuelve al principio en pausa');
  await remote.locator('#reconnect').click();
  await remote.waitForFunction(() => !document.querySelector('#play').disabled, { timeout: 30000 });
  check('reconectar el teléfono');
  await host.getByRole('button', { name: 'Control remoto', exact: true }).click();
  await host.getByRole('button', { name: 'Desconectar teléfono', exact: true }).click();
  await remote.waitForFunction(() => document.querySelector('#play').disabled);
  check('revocar sesión deshabilita el control');
  const offline = await browser.newPage();
  const requests = [];
  offline.on('request', req => { if (/^https?:/.test(req.url())) requests.push(req.url()); });
  await offline.goto(pathToFileURL(process.cwd() + '/dist/index.html').href);
  assert.equal(await offline.evaluate(() => window.pc311.listo), true);
  assert.equal(requests.length, 0);
  check('HTML local inicia sin solicitudes de red');
  assert.deepEqual(report.errors, []);
} catch (error) {
  report.failure = error.stack;
  console.error(error);
  process.exitCode = 1;
} finally {
  await writeFile('qa/remoto-verificacion.json', JSON.stringify(report, null, 2));
  await browser.close();
  server.close();
}
